id: I5F04CF58
legacy_id: P000352
ocr_import_info:
  bdrc_scan_id: W8722
  source: bdrc
  ocr_info:
    timestamp: '2020-03-14T10:52:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:26:13.018738+00:00'
last_modified: 2022-09-04 11:26:17.783791
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8722
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8722
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨ་བསེའི་བྱུང་ཁུངས་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ།
  author: དྲེའུ་ལྷས་གྲུབ་དབང ༠༢་ཀུན་དགའ་མི་འགྱུར་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9665959919636536
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1GS105577:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS105577
      total_pages: 36
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS105577.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9665959919636536
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
